### ISSUE TITLE
decide whether to make checkpoints and/or save/load system

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/cyberpunk-jam-2019#24]
Most games have checkpoints and/or save/load systems.
Figure out if we need something and implement it.

**Comment by AmerigoGazaway** [comment]
Was thinking maybe this (save points) could be the purpose of hidden doors. Either that or a computer terminal of some sort. Maybe it takes you to a little room with a computer terminal to save data

**Comment by plexsoup** [comment]
not necessary
