### ISSUE TITLE
SFX plays twice when jumping down

### ISSUE THREAD

**Issue by AmerigoGazaway** [godot-wildlings/cyberpunk-jam-2019#62]
When player jumps down the "huh" SFX are doubled up/playing twice. Not a huge deal but makes a weird echo/phasing effect

**Comment by plexsoup** [comment]
Thanks. I hear it. Looking at the code now.

**Comment by plexsoup** [comment]
Solved in eab5931 - refactored "drop" mechanic. Added drop animation
