### ISSUE TITLE
Demonstrate the effects of attention deprivation? How?

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/cyberpunk-jam-2019#8]
> ATTENTION IS THE ONLY VIABLE CURRENCY
NOW.

**Comment by AmerigoGazaway** [comment]
Billboards everywhere, advertising, etc. The city has gone to shit and crime is rampant because everyone is plugged into network. Maybe the billboards could also have some of the label hints inside them

**Comment by plexsoup** [comment]
I added "Obey" to one of the background images. :)
